#! /bin/sh

printf "%s\n" "Crafting..." >&2
mulle-sde -v craft -V || exit 1


if [ ! -d test ]
then
   printf "%s\n" "Testing..." >&2
   mulle-env -c "mulle-sde -v test --no-memory-checker --serial"
fi
