language: c

dist: trusty
sudo: required

addons:
  apt:
    packages:
      - cmake
      - cmake-data

before_install:
   - curl -sS "https://www.mulle-kybernetik.com/dists/admin-pub.asc" | sudo apt-key add -
   - sudo ( echo "deb [arch=all] http://www.mulle-kybernetik.com `lsb_release -c -s` main" > "/etc/apt/sources.list.d/mulle-kybernetik.com-main.list" )
   - sudo apt-get update
   - sudo apt-get -y --allow-unauthenticated install mulle-build

script:
   - mulle-build -vv -V --bootstrap
   - mulle-test -vv -V
