/*
 *   This file will be regenerated by `mulle-project-versioncheck`.
 *   Any edits will be lost.
 */
#ifndef mulle_allocator_versioncheck_h__
#define mulle_allocator_versioncheck_h__

#if defined( MULLE__C11_VERSION)
# ifndef MULLE__C11_VERSION_MIN
#  define MULLE__C11_VERSION_MIN  ((4UL << 20) | (7 << 8) | 0)
# endif
# ifndef MULLE__C11_VERSION_MAX
#  define MULLE__C11_VERSION_MAX  ((5UL << 20) | (0 << 8) | 0)
# endif
# if MULLE__C11_VERSION < MULLE__C11_VERSION_MIN || MULLE__C11_VERSION >= MULLE__C11_VERSION_MAX
#  pragma message("MULLE__C11_VERSION     is " MULLE_C_STRINGIFY_MACRO( MULLE__C11_VERSION))
#  pragma message("MULLE__C11_VERSION_MIN is " MULLE_C_STRINGIFY_MACRO( MULLE__C11_VERSION_MIN))
#  pragma message("MULLE__C11_VERSION_MAX is " MULLE_C_STRINGIFY_MACRO( MULLE__C11_VERSION_MAX))
#  if MULLE__C11_VERSION < MULLE__C11_VERSION_MIN
#   error "mulle-c11 is too old"
#  else
#   error "mulle-c11 is too new"
#  endif
# endif
#endif

#endif
