/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_allocator_include_h__
#define _mulle_allocator_include_h__

// You can tweak the following #include with these commands.
// (Use 4F638AE4-A8F3-49F0-BC69-EFBBE1376CBB instead of mulle-c11 if there are duplicate entries)
//    remove:             `mulle-sourcetree mark mulle-c11 no-header`
//    rename:             `mulle-sde dependency|library set mulle-c11 include whatever.h`
//    reorder:            `mulle-sourcetree move mulle-c11 <up|down>`
//    toggle #include:    `mulle-sourcetree mark mulle-c11 [no-]import`
//    toggle public:      `mulle-sourcetree mark mulle-c11 [no-]public`
//    toggle optional:    `mulle-sourcetree mark mulle-c11 [no-]require`
//    remove for platform:`mulle-sourcetree mark mulle-c11 no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#include <mulle-c11/mulle-c11.h>   // mulle-c11

#endif
