/*
*   This file will be regenerated by `mulle-sde update|monitor`.
* Edits will be lost.
* Suppress this file with MULLE_SOURCETREE_TO_C_INCLUDE_FILE NONE|DISABLE.
*/

#ifndef _mulle_allocator_include_h__
#define _mulle_allocator_include_h__

# include <mulle-c11/mulle-c11.h>   // mulle-c11

#endif
