/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulle_allocator_include_h__
#define _mulle_allocator_include_h__

# include <mulle-thread/mulle-thread.h>   // mulle-thread

#endif
