#ifndef _mulle_allocator_dependencies_h__
#define _mulle_allocator_dependencies_h__

/* a central include file to keep dependencies out of the actual .c files
   the advantage: .c files can be moved to other projects and don't need
   to be edited. Also less typing...
*/

/* include header file automatically generated by mulle-c-sourcetree-update */
#if __has_include( "_dependencies.h")
# include "_dependencies.h"
#endif

/* add some more dependencies here */

#endif
