# cmake/_Headers.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
) 

set( PUBLIC_HEADERS
src/dependencies.h
src/mulle-allocator.h
src/mulle-allocator-struct.h
src/pointerarray.h
src/pointerset.h
src/version.h
)

set( TEST_ALLOCATOR_PUBLIC_HEADERS
src/mulle-test-allocator.h
src/mulle-test-allocator-struct.h
) 

