name: CI

on: [push]

env:
  BUILD_TYPE: release
  OTHER_PROJECTS: mulle-c/mulle-c-developer;

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - uses: mulle-sde/github-ci@v1

    - name: Add to path
      run:  echo "$HOME/bin" >> $GITHUB_PATH

    - name: Dump Build Environment
      run:  env

    - name: Mulle-SDE Fetch
      run: mulle-sde fetch

    - name: Mulle-SDE Craft
      run: mulle-sde craft --${BUILD_TYPE:-release}

    - name: Mulle-SDE Test
      run: mulle-sde test
